# Generated by Django 4.2 on 2023-04-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
