# Generated by Django 4.2 on 2023-04-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
